[theme]
primaryColor = "#FF4B4B"                 
backgroundColor = "#c5ebee"             
secondaryBackgroundColor = "#50e261"    
textColor = "#000000"                   
font = "sans serif"                     
